// Generated by scripts/sync-public-site-version.js from the stable release manifest.
(() => {
  const latestVersion = "v0.18.6";
  const apply = () => document.querySelectorAll('[data-latest-version]').forEach((node) => { node.textContent = latestVersion; });
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', apply, { once:true });
  else apply();
  window.LYRASTAGE_LATEST_VERSION = latestVersion;
})();
